config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  get "about" => "pages#about"
  get "terms" => "pages#terms"
  get "faq" => "pages#faq"
  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :tracker_projects, only: [:show]

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#login"
  delete 'logout' => 'sessions#logout'

  get "/signup" => "registrations#new", as: :signup
  post '/signup' => 'registrations#create'

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates :description, presence: true
  validate :due_date_not_in_future
  def  due_date_not_in_future
    if due != nil && id == nil
      if (due < Date.today)
        errors.add(:due, "date must be in future.")
      end
    end
  end

  has_many :comments, dependent: :destroy
  has_many :tasks, through: :comments
  belongs_to :project


  def self.as_csv
  CSV.generate do |csv|
    csv << column_names
    all.each do |task|
      csv << task.attributes.values_at(*column_names)
      end
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  before_action do
    @project = Project.find(params[:project_id])
  end

  before_action :current_user_has_tasks_permission

  # GET /tasks
  # GET /tasks.json
  def index
    # can refactor below by dropping == "specific"
    #
    # also can
    # if params this
    #   @tasks=@task.this
    # if params that
    #   @task= @task.that

    if params[:type] == "all" && params[:sort] == "description"
      @tasks = @project.tasks.order(:description)
    elsif params[:type] == "incomplete" && params[:sort] == "description"
      @tasks = @project.tasks.order(:description).where(complete: false)

    elsif params[:type] == "all" && params[:sort] == "complete"
      @tasks = @project.tasks.order(:complete)
    elsif params[:type] == "complete" && params[:sort] == "complete"
      @tasks = @project.tasks.order(:complete).where(complete: false)

    elsif params[:type] == "all" && params[:sort] == "due"
      @tasks = @project.tasks.order(:due)
    elsif params[:type] == "incomplete" && params[:sort] == "due"
      @tasks = @project.tasks.order(:due).where(complete: false)


    elsif params[:type] == "all"
      @tasks = @project.tasks
    elsif params[:type] == "incomplete"
      @tasks = @project.tasks.where(complete: false)
    else
      @tasks = @project.tasks.where(complete: false)
    end

    respond_to do |format|
      format.html
      format.csv { send_data @tasks.as_csv }
    end


  end

  def show
    @task = @project.tasks.find(params[:id])
    @comment = Comment.new
  end

  def new
    @task = @project.tasks.new
  end

  def edit
    @task = @project.tasks.find(params[:id])
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @task = @project.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task = @project.tasks.find(params[:id])
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
  end

  private

  def current_user_has_tasks_permission
    if (@project.memberships.pluck(:user_id).include? current_user.id) || (current_user.admin == true)
      true
    else
      raise AccessDenied
    end
  end

  def task_params
    params.require(:task).permit(:description, :complete, :due, :project_id)
  end



end

app/helpers/tasks_helper.rb
module TasksHelper

end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <div class="form-horizontal">

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-6">
        <%= render "shared/errors", model: @task %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, class:" col-sm-1 "%>
      <div class="col-sm-3">
        <%= f.text_field :description, class:"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :due, class:"col-sm-1" %>
      <div class="col-sm-2">
        <%= f.date_field :due, class:"form-control" %>
      </div>
    </div>

    <% if (params.has_key?(:id)) %>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <div class="checkbox">
          <label>
            <%= f.check_box :complete %> Complete
          </label>
        </div>
      </div>
    </div>
    <%end%>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    </div>
  </div>


<% end %>

app/views/tasks/edit.html.erb
<div class="page-header">
  <h1>Edit Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
<div class="pull-right">
  <small>
    <%= link_to_unless_current("All", project_tasks_path(@project, type: "all")) %> |
    <% if params[:type] == nil %>
    Incomplete
    <% else %>
    <%= link_to_unless_current("Incomplete", project_tasks_path(@project, type: "incomplete")) %>
    <% end %>
  </small>
  <%= link_to 'Create Task', new_project_task_path(@project), class:"btn btn-info btn-large" %>
</div>
  <h1>Tasks for <%= @project.name %></h1>
</div>

<ol class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li><%= link_to @project.name, @project %></li>
  <li class="active">Tasks</li>
</ol>


<table class="table">
  <thead>
    <tr>
      <% if params[:type] == "all"  %>
        <th><%= link_to("Description", project_tasks_path(@project, sort: "description", type: "all")) %></th>
      <% else %>
        <th><%= link_to("Description", project_tasks_path(@project, sort: "description", type: "incomplete")) %></th>
      <% end %>

      <% if params[:type] == "all"  %>
        <th><%= link_to("Complete", project_tasks_path(@project, sort: "complete", type: "all")) %></th>
      <% else %>
        <th><%= link_to("Complete", project_tasks_path(@project, sort: "complete", type: "incomplete")) %></th>
      <% end %>

      <% if params[:type] == "all"  %>
        <th><%= link_to("Due Date", project_tasks_path(@project, sort: "due", type: "all")) %></th>
      <% else %>
        <th><%= link_to("Due Date", project_tasks_path(@project, sort: "due", type: "incomplete")) %></th>
      <% end %>
      <th>

      </th>

    </tr>
  </thead>


  <tbody>

    <% @tasks.each do |task| %>
    <% require 'date' %>
    <% current_date = Date.today %>
      <%if task.due == nil %>
        <tr>
          <td><%= link_to task.description, project_task_path(@project, task)%> <span class="badge"> <%= task.comments.count %></span></td>
          <td><%= task.complete%></td>
          <td>Blank</td>
          <td>
            <div class="pull-right" >
              <%= link_to 'Edit ', edit_project_task_path(@project, task), class:"btn btn-info btn-large", id:"delete" %>
              <%= link_to " ", project_task_path(@project, task), class:"glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
        </td>
        </tr>
      <%elsif (task.due - current_date).to_i < 7 %>
        <tr class="danger">
          <td><%= link_to task.description, project_task_path(@project, task)%> <span class="badge"> <%= task.comments.count %></span></td>
          <td><%= task.complete%></td>
          <td><%= task.due%></td>
          <td>
            <div class="pull-right">
              <%= link_to 'Edit ', edit_project_task_path(@project, task), class:"btn btn-info btn-large" %>
              <%= link_to " ", project_task_path(@project, task), class:"glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <%else%>
        <tr>
          <td><%= link_to task.description, project_task_path(@project, task)%> <span class="badge"> <%= task.comments.count %></span></td>
          <td><%= task.complete %></td>
          <td><%= task.due %></td>
          <td>
            <div class="pull-right">
              <%= link_to 'Edit ', edit_project_task_path(@project, task), class:"btn btn-info btn-large" %>
              <%= link_to " ", project_task_path(@project, task), class:"glyphicon glyphicon-remove", method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>


<br>
<hr></hr>

<br>

app/views/tasks/new.html.erb
<div class="page-header">
  <h1>New Task</h1>
</div>

<%= render 'form' %>

app/views/tasks/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_project_task_path(@project, @task),
    class:"btn btn-info btn-large" %>
  </div>
  <h1><%= @task.description %></h1>


</div>
<ol class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li><%= link_to @project.name, @project %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class="active">Show</li>
</ol>
<p>
  <strong>Due:</strong>
  <%= @task.due %>
</p>
<p>
  <strong>Complete:</strong>
  <%= @task.complete %>
</p>

<h3>Comments</h3>
<% @task.comments.each do |comment| %>
<div class="row">
  <div class="col-md-3">
    <% if comment.user == nil %>
    <%= "deleted user" %>
    <% else %>
    <%= link_to(comment.user.full_name, user_path(comment.user)) %>
    <% end %>
    <div class="text-muted">
      <%= "#{time_ago_in_words(comment.created_at)} ago" %>
    </div>
  </div>
  <div class="col-md-9">
    <%= comment.description %>
  </div>
</div>
<% end %>
<% if current_user.present? %>

<% end %>
<br>
<br>
<br>

<%= form_for [@project, @task, @comment] do |f| %>

  <div class="form-horizontal">

    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.text_area :description, class:"form-control" %>
      </div>
    </div>

    <div class="form-group">
      <div class= "col-md-offset-3 col-md-9">
          <%= f.submit "Add Comment", class:"btn btn-primary" %>
      </div>
    </div>
  </div>

<% end %>