config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  get "about" => "pages#about"
  get "terms" => "pages#terms"
  get "faq" => "pages#faq"
  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :tracker_projects, only: [:show]

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#login"
  delete 'logout' => 'sessions#logout'

  get "/signup" => "registrations#new", as: :signup
  post '/signup' => 'registrations#create'

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :delete_all
  has_many :users, through: :memberships

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController <  ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :current_user_has_project_permission, except: [:index, :new, :create, :destroy]
  before_action :current_user_is_owner_to_edit, only: [:edit, :update, :destroy]
  before_action :pivotal_projects_check, only: [:index]


  def index
    if current_user.admin == true
      @projects = Project.all
    else
      @projects = current_user.projects
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      Membership.create!(
        user_id: current_user.id,
        project_id: @project.id,
        role: "owner",
      )
      redirect_to project_tasks_path(@project), notice: 'Project successfully created'
    else
      render :new
    end
  end

  def show
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end



  private

  def project_params
    params.require(:project).permit(:name)
  end

  def pivotal_projects_check
    if current_user.pivotal_token != nil
      @pivotal_projects = API.new.pivotal_projects(current_user)
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  def current_user_has_project_permission
    if (@project.memberships.pluck(:user_id).include? current_user.id) || (current_user.admin == true)
      true
    else
      raise AccessDenied
    end
  end

  def current_user_is_owner_to_edit
    # where(role: "owner", user_id: current_user)
    current_membership = @project.memberships.where(user_id: current_user.id)
    current_membership.each do |membership|
      if (membership.role == "owner") || (current_user.admin == true)
        @current_project_owner = true
      else
        @current_project_owner = false
        raise AccessDenied
      end
    end
  end


end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

<div class="form-horizontal">
  <div class="form-group">
    <div class= "col-sm-offset-1 col-sm-6">
      <%= render "shared/errors", model: @project %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :name, class:"col-sm-1" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class:"form-control"%>
    </div>    
  </div>

    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-11">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    </div>

</div>
<% end %>

app/views/projects/edit.html.erb
<div class="page-header">
  <h1>Edit Project</h1>
</div>
<%= render "form" %>

app/views/projects/index.html.erb
<%= page_header "Projects" do %>
  <%= link_to 'Create Project', new_project_path, class:"btn btn-info btn-large" %>
<% end %>

<table class="table">
  <thead>
    <th>
      Name
    </th>
    <th>
      Members
    </th>
    <th>
      Tasks
    </th>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class = "">
          <%= link_to(project.name, project_path(project)) %>
        </td>
        <td>
          <%= link_to project.memberships.count, project_memberships_path(project) %>
        </td>
        <td>
          <%= link_to project.tasks.count, project_tasks_path(project) %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

<hr>

<div class="page-header">
  <h1>Pivotal Tracker Projects</h1>
</div>

<table class="table">
  <thead>
    <th>
      Name
    </th>
  </thead>
  <tbody>
    <% unless @pivotal_projects == nil %>
    <% @pivotal_projects.each do |project|%>
    <tr>
      <td>
        <%= link_to project[:name], tracker_project_path(project[:id]) %>
      </td>
    </tr>
    <%end%>
    <% end %>
  </tbody>
</table>
<hr>

app/views/projects/new.html.erb
<div class="page-header">
  <h1>New Project</h1>
</div>

<%= render "form" %>

app/views/projects/show.html.erb
<div class="page-header">
  <div class = 'pull-right'>
    <% current_membership = @project.memberships.where(user_id: current_user.id) %>
    <% current_membership.each do |membership| %>
    <% @membership_role = membership.role %>
    <% if (membership.role == "owner")%>
    <%= link_to 'Edit', edit_project_path, class:"btn btn-info btn-large" %>
    <% end %>
    <% end %>
    <% if current_user.admin == true && @membership_role != "owner" %>
    <%= link_to 'Edit', edit_project_path, class:"btn btn-info btn-large" %>
    <% end %>
  </div>
  <h1>
    <%= @project.name %>
  </h1>
</div>

<ol class="breadcrumb">
  <li><a href="/projects">Projects</a></li>
  <li class="active"><%= @project.name %></li>
</ol>

<%= link_to pluralize(@project.tasks.count, "Task"),
            project_tasks_path(@project) %>
<br><br>
<%= link_to pluralize(@project.memberships.count, "Member"),
            project_memberships_path(@project)%>
<br><br>
<% current_membership = @project.memberships.where(user_id: current_user.id) %>
<% current_membership.each do |membership| %>
  <% if membership.role == "owner" %>
    <div class="well">
      <strong>Delete Project</strong>
      <br><br>
      <p>
        Deleting this project will delete <%= @project.memberships.count %> memberships,
        <%= @project.tasks.count %> tasks, and associated comments.
      </p>
      <br>
      <%= link_to 'Delete', @project, class:"btn btn-danger btn-large",
      method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  <% end %>
<% end %>
<% if current_user.admin == true && @membership_role != "owner" %>
  <div class="well">
    <strong>Delete Project</strong>
    <br><br>
    <p>
      Deleting this project will delete <%= @project.memberships.count %> memberships,
      <%= @project.tasks.count %> tasks, and associated comments.
    </p>
    <br>
    <%= link_to 'Delete', @project, class:"btn btn-danger btn-large",
    method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
<% end %>