config/routes.rb
Rails.application.routes.draw do

  root "pages#index"
  get "about" => "pages#about"
  get "terms" => "pages#terms"
  get "faq" => "pages#faq"
  resources :users

  resources :projects do
    resources :tasks do
      resources :comments
    end
    resources :memberships
  end

  resources :tracker_projects, only: [:show]

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#login"
  delete 'logout' => 'sessions#logout'

  get "/signup" => "registrations#new", as: :signup
  post '/signup' => 'registrations#create'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= content_for(:title) || "gCamp" %></title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">


  <title>Jumbotron Template for Bootstrap</title>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/projects">gCamp</a>
      </div>


      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            My Projects
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <% current_user.projects.each do |project| %>
              <li><%= link_to project.name, project %></li>
            <% end %>
            <li class="divider"></li>
            <li><a href="/projects/new">New Project</a></li>
          </ul>
        </li>
        <li>
          <%= link_to "Users", users_path %>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="<%= 'active' if current_page?(current_user)%>">
            <%= link_to(current_user.first_name + " " +current_user.last_name, current_user) %></li>
          <li><%= link_to("Sign Out", logout_path, method: :delete) %></li>
        <% else %>
          <li class="<%= 'active' if (current_page?(signup_path)) || (@signup_error) %>"
            ><a href="/signup">Sign Up</a></li>
          <li class="<%= 'active' if (current_page?(login_path)) || (@login_error)%>"
              ><a href="/login">Sign In</a></li>
        <% end %>
      </ul>
    </div>
  </div>
  <br></br>

  <% if @index_page %>
    <div class="main_page">
  <% else %>
    <div class="container">
  <% end %>
  <% if notice != nil %>
    <br>
    <p id="notice", class="alert alert-success"><%= notice %></p>
  <%end%>
  <%= yield %>
    </div>
    <div class="container">
      <footer style="text-align:center">
        <p>
          <%= link_to_unless_current("Home", root_path) %> |
          <%= link_to_unless_current("About", about_path) %> |
          <%= link_to_unless_current("Terms", terms_path) %> |
          <%= link_to_unless_current("FAQ", faq_path) %>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>gCamp</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <title>Jumbotron Template for Bootstrap</title>
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/projects">gCamp</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li class="<%= 'active' if current_page?(current_user)%>">
          <%= link_to(current_user.first_name + " " +current_user.last_name, current_user) %></li>
          <li><%= link_to("Sign Out", logout_path, method: :delete) %></li>
        <% else %>
          <li class="<%= 'active' if (current_page?(signup_path)) || (@signup_error) %>"
          ><a href="/signup">Sign Up</a></li>
          <li class="<%= 'active' if (current_page?(login_path)) || (@login_error)%>"
          ><a href="/login">Sign In</a></li>
        <% end %>

      </ul>
      </div>
    </div>
    <br></br>

    <% if @index_page %>
      <div class="main_page">
    <% else %>
      <div class="container">
    <% end %>
      <% if notice != nil %>
      <br>
        <p id="notice", class="alert alert-success"><%= notice %></p>
      <%end%>
    <%= yield %>
      </div>
      <div class="container">
        <footer>
          <div class="pull-left">
            <%= link_to_unless_current("Home", root_path) %> |
            <%= link_to_unless_current("About", about_path) %> |
             <%= link_to_unless_current("Terms", terms_path) %> |
             <%= link_to_unless_current("FAQ", faq_path) %>
             <% if current_user != nil %>
               | <%= link_to_unless_current("My Projects", projects_path) %>
             <% end %>

          </div>

            <div class="pull-right">
              <%= link_to "https://linkedin.com/in/hostetjm/" do %>
                <%= image_tag("LinkedIn.png", width: "20em") %>
              <% end %>
              <%= link_to "https://github.com/Jeff-Hostetler" do %>
                <%= image_tag("GitHub.png", width: "20em") %>
              <% end %>
              <%= link_to "https://twitter.com/JeffHosBoss" do %>
                <%= image_tag("Twitter.png", width: "20em") %>
              <% end %>
              <%= link_to "http://www.galvanize.it/school" do %>
                <%= image_tag("galvanize.jpeg", width: "70em") %>
              <% end %>
            </div>
          
        </footer>
      </div>
  </body>
</html>